---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
kauffman.ds <- read_csv("Main Street Entrepreneurship.csv")

pcgdp.ds <- read_csv("gmpPCGDP.csv")
```
```{r}
library(skimr)

survive.df <- kauffman.ds %>% 
  select(Location, 'Index Year', Location_name, Survival_Rate) %>% 
  rename(Year = 'Index Year')

skim(survive.df)
```

```{r}
survive.df %>% 
  mutate(IsMissing = if_else(is.na(Survival_Rate), 1, 0)) %>% 
  group_by(Year, IsMissing) %>% 
  summarize(n = n())
```

```{r}
survive.df <- survive.df %>% 
  filter(!is.na(Survival_Rate)) %>% 
  arrange(Location_name, Year)
head(survive.df, 10)
```

```{r}
skim(pcgdp.ds)
```

```{r}
pcgdp.df <- pcgdp.ds %>% 
  filter(!is.na(GeoName))
```
```{r}
pcgdp.df <- pcgdp.df %>% 
  select(GeoFIPS, GeoName, `2001`:`2016`)
skim(pcgdp.df)
```
```{r}
pcgdp.df <- pcgdp.df %>% 
  gather(Year, GDP_PC, `2001`:`2016`) %>% 
  arrange(GeoFIPS, Year)
head(pcgdp.df, 10)
```

```{r}
pcgdp.df <- pcgdp.df %>% 
  filter(GeoFIPS != "00998")
head(pcgdp.df, 10)
```

```{r}
library(stringr)

pcgdp.df <- pcgdp.df %>% 
  mutate(GeoName = str_remove(GeoName, ",.*"))
head(pcgdp.df, 10)
```

```{r}
pcgdp.df <- pcgdp.df %>% 
  rename(Location = GeoFIPS,
         Location_name = GeoName) %>% 
  mutate(Location = as.integer(Location),
         Year = as.integer(Year))
```
```{r}
survive.compare <- survive.df %>% 
  select(Location, Location_name) %>% 
  distinct()
pcgdp.compare <- pcgdp.df %>% 
  select(Location, Location_name) %>% 
  distinct()
all_equal(survive.compare, pcgdp.compare)
```

```{r}
skim(survive.df$Year)
```

```{r}
skim(pcgdp.df$Year)
```

```{r}
survive.df <- survive.df %>% 
  filter(Year >= 2001)
```

```{r}
survive.compare <- survive.df %>% 
  select(Location, Location_name) %>% 
  distinct()
pcgdp.compare <- pcgdp.df %>% 
  select(Location, Location_name) %>% 
  distinct()
all_equal(survive.compare, pcgdp.compare)
```

```{r}
head(survive.df, 10)
```

```{r}
survive.df <- survive.df %>% 
  filter(Location > 56)
```
```{r}
survival.df <- inner_join(survive.df, pcgdp.df, by = c("Location", "Year"))
head(survival.df, 10)
```

```{r}
survival.df <- survival.df %>% 
  select(-Location_name.y) %>% 
  rename(MSA = Location_name.x) %>% 
  mutate(as.factor(MSA))
head(survival.df, 10)
```

```{r}
survival.df %>% 
  count(MSA)
```

```{r}
ggplot(survival.df, aes(x=GDP_PC)) +
  geom_histogram()
```
```{r}
survival.df <- survival.df %>% 
  mutate(logGDP_PC = log(GDP_PC))
```
```{r}
ggplot(survival.df, aes(x=logGDP_PC)) +
  geom_histogram()
```
```{r}
ggplot(survival.df, aes(y = Survival_Rate, x = logGDP_PC)) +
  geom_point() +
  geom_smooth(method = "loess")
```

