---
title: "Multilevel"
output: html_document
---
```{r setup, include = FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
survival.df <- survival.df %>% 
  group_by(AveGDP = mean(logGDP_PC)) %>% 
  mutate(cenGDP = logGDP_PC - AveGDP,
         Year = as.factor(Year))
```

```{r}
library(brms)
library(sjPlot)
library(sjstats)
```

```{r}
my.prior <- set_prior("normal(0,5)", class = "b")

set.seed(08022003)
dist <- data_frame(beta = rnorm(1000, 0, 5))
```
```{r}
intercept.model <- brm(Survival_Rate ~ (1 | Location),
                       data = survival.df, chains = 2)
```
```{r}
summary(intercept.model)
```
#popultion effect is same as fixed effects

```{r}
plot_model(intercept.model, type = "re") + 
  theme_bw()
```
```{r}
icc(intercept.model)
```
```{r}
random_year.model <- brm(Survival_Rate ~ Year + (1 | Location),
                         data = survival.df, chains = 2, prior = my.prior)
```
```{r}
summary(random_year.model)
```
```{r}
plot_model(random_year.model) +
  theme_bw()
```

```{r}
tidy_stan(random_year.model)
```

```{r}
random_fixed.model <- brm(Survival_Rate ~ cenGDP + Year + (1 | Location), data = survival.df, chains = 2, prior = my.prior)
```
```{r}
summary(random_fixed.model)
```
```{r}
plot_model(random_fixed.model) +
  theme_bw()
```
```{r}
plot_model(random_fixed.model, type = "pred", terms = c("cenGDP")) +
  theme_bw()
```
```{r}
prior_summary(random_fixed.model)
```
```{r}
hybrid.rf.model <- brm(Survival_Rate ~ cenGDP + AveGDP + Year + (1 | Location), data = survival.df, chains = 2, prior = my.prior)
```

```{r}
summary(hybrid.rf.model)
```

```{r}
plot_model(hybrid.rf.model) +
  theme_bw()
```

```{r}

```

